# syntax=docker/dockerfile:1
FROM golang:1.23.6-bookworm

ARG MIGRATE_VERSION=4.18.3
ARG CHECKSUM=40308b01c14cc8eccc908db8605f8aff7097c99e9748852cb8295f82c3ab234e

ADD --checksum=sha256:${CHECKSUM} https://github.com/golang-migrate/migrate/releases/download/v${MIGRATE_VERSION}/migrate.linux-amd64.deb /tmp/migrate.deb

RUN apt-get update && \
    apt-get install -y \
    make \
    # postgresql-client \
    && apt-get install -y /tmp/migrate.deb && \
    rm -v /tmp/migrate.deb

WORKDIR /usr/src/app

COPY . .

# Add github.com/cartesi/rollups-node to the image
ADD https://github.com/cartesi/rollups-node.git#v2.0.0-alpha.2 /usr/src/app/rollups-node

# Use the entrypoint script instead of running commands directly
ENTRYPOINT ["/usr/src/app/entrypoint-db.sh"]